---
- name: Webserver Playbook
  hosts: dev
  become: yes
  remote_user: ansiblekey
  become_method: sudo
  gather_facts: yes

  tasks:
      - name: Install apache2 on Ubuntu
        ansible.builtin.apt:
            name: apache2
            update_cache: yes
            state: present
        when: ansible_facts['os_family'] == "Debian"

      - name: Copy index.html
        ansible.builtin.copy:
            src: index.html-ubuntu
            dest: /var/www/html/index.html
        when: ansible_facts['os_family'] == "Debian"
        notify:
            - Restart apache
     
      - name: Install httpd on CentOS
        ansible.builtin.yum:
            name: httpd
            update_cache: yes
            state: present
        when: ansible_distribution == "CentOS"

      - name: Copy index.html
        ansible.builtin.copy:
            src: index.html-centos
            dest: /var/www/html/index.html
        when: ansible_distribution == "CentOS"
        notify:
            - Restart httpd

  handlers:
      - name: Restart apache
        ansible.builtin.service:
            name: apache2
            state: restarted
      - name: Restart httpd
        ansible.builtin.service:
            name: httpd
            state: restarted
